
export const portfolioProjects = [
  {
    id: 'techstore',
    title: 'TechStore',
    shortDescription: 'Современный интернет-магазин электроники с удобной системой фильтрации и быстрым оформлением заказов.',
    image: '/placeholder.svg',
    category: 'ecommerce',
    categoryLabel: 'E-commerce',
    year: '2024',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'PostgreSQL'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'devcorp',
    title: 'DevCorp',
    shortDescription: 'Корпоративный сайт IT-компании с современным дизайном и адаптивной версткой.',
    image: '/placeholder.svg',
    category: 'corporate',
    categoryLabel: 'Корпоративный',
    year: '2024',
    technologies: ['React', 'Next.js', 'TypeScript', 'Framer Motion'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'fintech',
    title: 'FinTech',
    shortDescription: 'Веб-приложение для управления финансами с аналитикой и отчетностью.',
    image: '/placeholder.svg',
    category: 'webapp',
    categoryLabel: 'Веб-приложение',
    year: '2024',
    technologies: ['React', 'Redux', 'Chart.js', 'Express', 'MongoDB'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'styleshop',
    title: 'StyleShop',
    shortDescription: 'Магазин модной одежды с интуитивным интерфейсом и персонализированными рекомендациями.',
    image: '/placeholder.svg',
    category: 'ecommerce',
    categoryLabel: 'E-commerce',
    year: '2023',
    technologies: ['Vue.js', 'Nuxt.js', 'Vuetify', 'Laravel', 'MySQL'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'taskflow',
    title: 'TaskFlow',
    shortDescription: 'Система управления проектами и задачами для команд разработки.',
    image: '/placeholder.svg',
    category: 'webapp',
    categoryLabel: 'Веб-приложение',
    year: '2023',
    technologies: ['React', 'TypeScript', 'Material-UI', 'NestJS', 'PostgreSQL'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'medcenter',
    title: 'MedCenter',
    shortDescription: 'Сайт медицинского центра с онлайн записью к врачам и личным кабинетом пациента.',
    image: '/placeholder.svg',
    category: 'corporate',
    categoryLabel: 'Корпоративный',
    year: '2023',
    technologies: ['React', 'Bootstrap', 'PHP', 'MySQL'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'codecourse',
    title: 'CodeCourse',
    shortDescription: 'Платформа онлайн обучения программированию с интерактивными уроками.',
    image: '/placeholder.svg',
    category: 'webapp',
    categoryLabel: 'Веб-приложение',
    year: '2023',
    technologies: ['React', 'Redux', 'Node.js', 'Socket.io', 'MongoDB'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'foodexpress',
    title: 'FoodExpress',
    shortDescription: 'Сервис доставки еды с трекингом заказов в реальном времени.',
    image: '/placeholder.svg',
    category: 'webapp',
    categoryLabel: 'Веб-приложение',
    year: '2022',
    technologies: ['React Native', 'Redux', 'Node.js', 'Express', 'MongoDB'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'homestore',
    title: 'HomeStore',
    shortDescription: 'Интернет-магазин товаров для дома с AR-примеркой мебели.',
    image: '/placeholder.svg',
    category: 'ecommerce',
    categoryLabel: 'E-commerce',
    year: '2022',
    technologies: ['React', 'Three.js', 'WebXR', 'Node.js', 'PostgreSQL'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'securebank',
    title: 'SecureBank',
    shortDescription: 'Мобильное банковское приложение с повышенной безопасностью.',
    image: '/placeholder.svg',
    category: 'mobile',
    categoryLabel: 'Мобильное',
    year: '2022',
    technologies: ['React Native', 'TypeScript', 'Blockchain', 'Node.js'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'eduplatform',
    title: 'EduPlatform',
    shortDescription: 'Образовательная платформа для школьников с геймификацией.',
    image: '/placeholder.svg',
    category: 'webapp',
    categoryLabel: 'Веб-приложение',
    year: '2022',
    technologies: ['Vue.js', 'Vuex', 'Firebase', 'PWA'],
    demoUrl: '#',
    githubUrl: '#'
  },
  {
    id: 'fittracker',
    title: 'FitTracker',
    shortDescription: 'Мобильное приложение для отслеживания фитнес-активности и здоровья.',
    image: '/placeholder.svg',
    category: 'mobile',
    categoryLabel: 'Мобильное',
    year: '2021',
    technologies: ['Flutter', 'Dart', 'Firebase', 'HealthKit'],
    demoUrl: '#',
    githubUrl: '#'
  }
];
